[package]
name = "totp"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = "symbols"
panic = "abort"

[dependencies]
base32 = "0.5.1"
totp-lite = "2.0.1"
